### ISSUE TITLE
jtool dylib signing error

### ISSUE THREAD

**Issue by haniag** [BishopFox/bfinject#1]
Getting this error on i7 11.1, running LiberiOS 11.0.3:

    -bash-3.2# bash bfinject -p 813 -l /jb/bfinject/test.dylib
    [+] Injecting into '/var/containers/Bundle/Application/E7C4881E-DA00-4DE0-83B1-463896AECD42/Twitter.app/Twitter'
    [+] Getting Team ID from target application...
    [+] Signing injectable .dylib with Team ID com.atebits.Tweetie2 and platform entitlements...
    jtool dylib signing error. barfing.
    total 264
    -rwxr-xr-x  1 root  wheel  133216 Jan 23 16:56 bffd24d9a145056f32ee3b9599c3a3c8.dylib

**Comment by 0xhaggis** [comment]
See https://github.com/BishopFox/bfinject/issues/2.
