### ISSUE TITLE
NetCat shows "error" ip address when using cellular network.

### ISSUE THREAD

**Issue by DeviLeo** [BishopFox/bfinject#10]
My device is iPhone 7 (Global), iOS 11.1.1(15B150), using LiberiOS 11.0.3 jailbreak.

If I tap "YES" after decryption complete, the app will get stuck.

By the way, I ssh to my device by usbmuxd.

See the screenshot below.
![img_6131](https://user-images.githubusercontent.com/4043644/35433117-36bdab98-02bd-11e8-9ca9-fb3db557485f.PNG)

**Comment by 0xhaggis** [comment]
Heh, I assumed folks would be using wifi or usbmuxd, which was a poor assumption! I've updated the code, it works properly now.
