### ISSUE TITLE
Which location are .ipa files stored once the apps are decrypted?

### ISSUE THREAD

**Issue by kallism** [BishopFox/bfinject#11]

**Comment by jakibaki** [comment]
Look [here](https://github.com/BishopFox/bfinject#decrypt-app-store-apps) inside the readme!

There's a whole section about it.

**Comment by kallism** [comment]
I have read it before sending this. It does not say anywhere where the file is stored. It just that I will receive a UI alert to spawn from which I can download the ipa. However, I have tried to decrypt imessage stickers and unfortunately I don’t get the UI alert so I tried to locate where the decrypted  .ipa is stored but could not find it.

**Comment by Mila432** [comment]
what are you even doing here if you cant read?

>Alternatively, check the console log for the device, it will tell you where the decrypted IPA is stored. For example:

>[dumpdecrypted] Wrote /var/mobile/Containers/Data/Application/6E6A5887-8B58-4FC5-A2F3-7870EDB5E8D1/Documents/decrypted-app.ipa

**Comment by kallism** [comment]
@Mila432 the console log doesn’t tell where the decrypted IPA is. I am not sure if you have entered a command to get this information.

**Comment by 0xhaggis** [comment]
The console log most definitely does tell you the location. I've also made the popups more robust and they should show up in all cases now.
