### ISSUE TITLE
[!] Unknown jailbreak. Aborting.

### ISSUE THREAD

**Issue by jhilgert** [BishopFox/bfinject#12]
Using bfinject on an iPhone 6S running iOS 11.1.2 and LiberiOS 11.0.3 results in "[!] Unknown jailbreak. Aborting.". 
Any ideas on that?

**Comment by jhilgert** [comment]
Okay, your wrapper shell script checks the wrong location for jtool in liberios... Changed that to /usr/local/bin... instead of /jb/usr/local/bin

**Comment by devAlikhani** [comment]
i get this error with Electra, any ideas?

**Comment by masbog** [comment]
same as me, i got this error with Th0r-2 Jailbreak...

**Comment by masbog** [comment]
same as me, i got this error with Th0r-2 Jailbreak...

**Comment by PeterHdd** [comment]
same
