### ISSUE TITLE
[!] "xxx.app" was not uniquely found, please check your criteria.

### ISSUE THREAD

**Issue by iosdec** [BishopFox/bfinject#14]
This happens when I use either the PID, the executable name or the .app name.

Here's some examples:
_bash bfinject -P flipbounce.app -L test_
_bash bfinject -P flipbounce -L test_

Here's an example of when I use the PID:
_bash bfinject -p flipbounce.app -L test_

**Output:**
[+] Electra detected.
cp: '/bootstrap/usr/local/bin/bfinject4realz' and '/bootstrap/usr/local/bin/bfinject4realz' are the same file
[+] Injecting into ''
[+] Getting Team ID from target application...
[+] WARNING: No Team ID found. Continuing regardless, but expect weird stuff to happen.
[+] Thinning dylib into non-fat arm64 image
[+] Signing injectable .dylib with Team ID  and platform entitlements...
jtool /bootstrap/usr/local/bin/ signing error. barfing.

**Research**
After reviewing the script, it seems like there's a problem with grep. Here's an example:
_ps -ax | grep flipbounce_

**Output**
_Killed_

**Comment by 0xhaggis** [comment]
"Killed" messages occur when your jailbreak is broken. It's iOS killing a process, usually due to codesigning problems. It could be either ps or grep getting killed, there's not enough info to say. Regardless, try rebooting and rejailbreaking. On Electra, make sure "Tweaks" is disabled.

**Comment by iosdec** [comment]
Ahhhhh makes perfect sense! Thanks for your support. I uninstalled electra, re-jailbroke with tweaks disabled, used the bin pack command that is displayed when you SSH into the device, and all works perfect!
