### ISSUE TITLE
jtool dylib signing error. barfing.

### ISSUE THREAD

**Issue by Sacmunraga** [BishopFox/bfinject#2]
This error gets thrown while I try to decrypt applications. I believe this issue is due to the .dylib not being signed.

[+] Injecting into '/var/containers/Bundle/Application/D98C23B4-8B41-49E8-9858-B46B77D770DD/Reddit.app/Reddit'
[+] Getting Team ID from target application...
[+] Signing injectable .dylib with Team ID com.reddit.Reddit and platform entitlements...
jtool dylib signing error. barfing.

Upon reviewing the code, line 159 : jtool --sign platform --ent entitlements.xml --inplace --teamid $TEAMID $DYLIB_PATH > /dev/null 2>&1 is where the error occurs. Specifically, the platform and --teamid are what cause the errors. tool doesn't recognize those two arguments.

**Comment by stek29** [comment]
#1 duplicate :\

**Comment by Sacmunraga** [comment]
Is there a solution?

**Comment by 0xhaggis** [comment]
Yes, there were two show-stopping bugs. Please pull the latest changes and try again.

**Comment by Sacmunraga** [comment]
Thanks bro
