### ISSUE TITLE
Error, no Team ID. Wat.

### ISSUE THREAD

**Issue by Sacmunraga** [BishopFox/bfinject#3]
Hi its me again. I used the newest version, and now it says that there is no teamid. Starting from line 122, I ran jtool --sig --ent "$BINARY" (which the shell code itself does) and it shows all of the information for the signature, so it must be something with the shell code after it - 2> /dev/null | grep 'Team ID' | head -n1 |sed 's/ //g'|cut -f2 -d:|cut -f1 -d\(`. As I am no shell code guru I am stuck again, any help?

**Comment by 0xhaggis** [comment]
Which app is this?

**Comment by 0xhaggis** [comment]
In the meantime I've pushed a change that (a) tries harder to get the right Team ID, and (b) throws a warning instead of an error if no Team ID is found. Give it a whirl!

**Comment by Sacmunraga** [comment]
Electra, b7. The thing is, in the last version it found the identifier with ease..., the problem was with jtool. Now it’s vice versa it seems.

**Comment by Sacmunraga** [comment]
Whoops just posted my reply, will do.

**Comment by 0xhaggis** [comment]
Ah, ok, Electra is unsupported. It won't work. The jtool is different than the one on LiberiOS, which has built-in features to mark binaries as "platform". Electra doesn't have that, so it simply won't work. Like the docs state: LiberiOS only.

**Comment by 0xhaggis** [comment]
Ok, I've pushed a new version that adds support for Electra by doing a simple check: if /bootstrap/inject_criticald exists, it's assumed you're using Electra and acts accordingly. If not, it's assumed you're using LiberiOS. Tested on Electra b7 and LiberiOS 11.0.3. Give it a go!

**Comment by Sacmunraga** [comment]
Ok that sounds great. Ill test it out.

**Comment by Sacmunraga** [comment]
It says 

[+] WARNING: No Team ID found. Continuing regardless, but expect weird stuff to happen.
[+] Signing injectable .dylib with Team ID  and platform entitlements...
jtool dylib signing error. barfing.
 and it goes downhill from there. Don't know why this happens, what jtool did you use with electra? 

Another thing is, ./jtool.liberios says "Operation not permitted" even after i chmoded it? Maybe thats why?

**Comment by 0xhaggis** [comment]
Dunno mate, it works fine on this end. Which app is it? I'll try to reproduce it.

**Comment by Sacmunraga** [comment]
Electra b7

**Comment by 0xhaggis** [comment]
Not the jailbreak. The app. Which app are you injecting into?

**Comment by Sacmunraga** [comment]
Sorry, my bad. Its the official Reddit app.

**Comment by 0xhaggis** [comment]
I see what's going on. I gotcha. Will need a couple of hours.

**Comment by Sacmunraga** [comment]
Np, do what you got to do.

**Comment by 0xhaggis** [comment]
Ok, I pushed in an update that detects Electra and LiberiOS properly, and adjusts behavior accordingly. I'm also packaging LiberiOS' copy of jtool for use on Electra, because Electra's jtool doesn't appear to support platform entitlements, which are required in order to pass kernel codesigning checks.

I've quickly tested it with Electra b7 on an iPhone 6 with iOS 11.0.2, and with LiberiOS 11.0.3 on an iPad Air2 with iOS 11.1.2. In both instances I was able to decrypt the Reddit app. 

Give it another shot please.

**Comment by snakeninny** [comment]
Tested with https://github.com/BishopFox/bfinject/raw/master/bfinject.tar and got this:

```
[+] Liberios detected
[+] Injecting into 'COMMAND'
[+] Getting Team ID from target application...
[+] WARNING: No Team ID found. Continuing regardless, but expect weird stuff to happen.
[+] Signing injectable .dylib with Team ID  and platform entitlements...
[bfinject] Getting tfp.
[bfinject] task_for_pid() failed with message (os/kern) failure!
[bfinject] Creating new remote thread
[bfinject] Failed to create thread in remote process. Is it really an App Store app?
[bfinject] thread_create() returned 268435459
[bfinject] errno = 2 = No such file or directory
[+] So long and thanks for all the fish.
```

@0xhaggis

**Comment by 0xhaggis** [comment]
@snakeninny it looks like you've typed the command incorrectly, but haven't supplied enough information to reproduce the issue. At the very least, please paste the command-line you used to get that error.

**Comment by snakeninny** [comment]
@0xhaggis My bad, I have misspelled the PID :\

With the correct PID I run:

```
bash bfinject -p 16630 -l /jb/bfinject/NEMQuickDelete_signed.dylib
```

But got this error:

```
[+] Liberios detected
[+] Injecting into '/var/containers/Bundle/Application/45B24BEA-20E4-4FBB-BE34-40BAD99BDAB9/neteasemusic.app/neteasemusic'
[+] Getting Team ID from target application...
[+] Signing injectable .dylib with Team ID 43B53CMF9D and platform entitlements...
[bfinject] Getting tfp.
[bfinject] Creating new remote thread
[bfinject] Thread ID: 3075 (0xc03)
[bfinject] Looking for RET gadget in the target app...
             gadget candidate: 0x100c70b70 ... Found @ 0x100c70b70
[bfinject] Fake stack frame is 536870912 bytes at 0x110f78000 in remote proc
[bfinject] Looking for '_pthread_set_self' in the target process...
[bfinject] Desired function '_pthread_set_self' is at 0x184733804
[bfinject] Setting registers with destination function
[bfinject] New CPU state:
             $pc = 0x184733804
             $sp = 0x128f78000
             $x0 = 0x0
             $x1 = 0x0
             $x2 = 0x0
             $x3 = 0x0
[bfinject] Resuming thread with hijacked regs
[bfinject] Waiting for thread to hit the infinite loop gadget...
[bfinject] We hit the infinite loop, call complete. Restoring stack and registers.
[bfinject] Looking for 'dlopen' in the target process...
[bfinject] Desired function 'dlopen' is at 0x1844f3460
[bfinject] Setting registers with destination function
[bfinject] New CPU state:
             $pc = 0x1844f3460
             $sp = 0x128f78000
             $x0 = 0x110f78000
             $x1 = 0xa
             $x2 = 0x0
             $x3 = 0x0
[bfinject] Resuming thread with hijacked regs
[bfinject] Waiting for thread to hit the infinite loop gadget...
[bfinject] We hit the infinite loop, call complete. Restoring stack and registers.
[bfinject] dlopen() returned 0x0 (FAILURE)
[bfinject] Looking for 'dlerror' in the target process...
[bfinject] Desired function 'dlerror' is at 0x1844f32b0
[bfinject] Setting registers with destination function
[bfinject] New CPU state:
             $pc = 0x1844f32b0
             $sp = 0x128f78000
             $x0 = 0x0
             $x1 = 0x0
             $x2 = 0x0
             $x3 = 0x0
[bfinject] Resuming thread with hijacked regs
[bfinject] Waiting for thread to hit the infinite loop gadget...
[bfinject] We hit the infinite loop, call complete. Restoring stack and registers.
[bfdecrypt] dlerror() returned: dlopen(/System/Library/Frameworks/d50dc7de4d78772a417f424b9f6cfd4c.framework/d50dc7de4d78772a417f424b9f6cfd4c.dylib, 10): no suitable image found.  Did find:
	/System/Library/Frameworks/d50dc7de4d78772a417f424b9f6cfd4c.framework/d50dc7de4d78772a417f424b9f6cfd4c.dylib: code signature invalid for '/System/Library/Frameworks/d50dc7de4d78772a417f424b9f6cfd4c.framework/d50dc7de4d78772a417f424b9f6cfd4c.dylib'
```

But I have signed the dylib with ldid already:

`ldid -S /Users/snakeninny/NEMQuickDelete_signed.dylib`

**Comment by 0xhaggis** [comment]
I tried to reproduce it by first signing simple.dylib with my Apple developer cert, then injecting it into an app with bfinject. It worked fine because jtool replaced the entitlements and signature, which is what I'd expect to see in your case, too.

Is there anything in the console log? Sometimes the kernel spits out useful errors like this:

kernel(AppleMobileFileIntegrity)[0] <Error>: Library Validation failed: Rejecting '/System/Library/Frameworks/simple.dylib' (Team ID: none, platform: no) for process 'Reddit(284)' (Team ID: 2TDUX39LX8, platform: no), **_reason: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?_**)

**Comment by snakeninny** [comment]
Thanks for your time! 
No extra log, I've pasted them all; BTW how should I sign my dylib? Does my method (using ldid) work? @0xhaggis

**Comment by 0xhaggis** [comment]
Don't sign anything, just leave it to bfinject. It's supposed to take care of all the codesigning and work like magic. 

You can emulate its behavior manually to grok what's happening:

```
jtool --sign platform --ent entitlements.xml --inplace --teamid 43B53CMF9D /jb/bfinject/NEMQuickDelete_signed.dylib
jtool --sig --ent /jb/bfinject/NEMQuickDelete_signed.dylib
bfinject4realz PID /jb/bfinject/NEMQuickDelete_signed.dylib
```

Try that and paste the responses.

**Comment by snakeninny** [comment]
Doesn't support fat dylib yet?

```
-bash-3.2# jtool --sign platform --ent entitlements.xml --inplace --teamid 43B53CMF9D /jb/bfinject/NEMQuickDelete_signed.dylib
Fat binary, big-endian,  2 architectures: armv7, arm64
Specify one of these architectures with -arch switch, or export the ARCH environment variable
-bash-3.2# jtool --sign platform -arch arm64 --ent entitlements.xml --inplace --teamid 43B53CMF9D /jb/bfinject/NEMQuickDelete_signed.dylib
Currently supported only on thin (single architecture) binaries
```

**Comment by Sacmunraga** [comment]
Ok, so itried with the latest build and now I get a jtool error. It’s tells me some kind of address error. I tried explicitly setting the teamid (TEAMID=com.reddit.Reddit) and tan it again but i keep getting the same jtool error. (1/2)

**Comment by 0xhaggis** [comment]
@snakeninny, no it doesn't. That's an oversight and a half!! I'll work on that.

@Sacmunraga "com.reddit.Reddit" is not a Team ID, it's an app identifier, so it won't work. You need the Team ID, which for Reddit is 2TDUX39LX8. If you got com.reddit.Reddit from bfinject, you're using an old version with a known (fixed) bug.

**Comment by 0xhaggis** [comment]
Just a quick note to say you can specify target apps by name instead of PID now, it's much more convenient.

**Comment by Sacmunraga** [comment]
Ok so this error has been fixed, thats for the help. Thread closed.

**Comment by hadoiz** [comment]
j???
