### ISSUE TITLE
md5sum: command not found

### ISSUE THREAD

**Issue by kubacizek** [BishopFox/bfinject#31]
Hi, after last update Core Utilities (8.29-1) it stopped working again. Now md5sum is not found. What now? Thanks

iPhone:~/bfinject root# bash bfinject -p 1566 -L test
[+] Electra detected.
bfinject: line 172: md5sum: command not found
bfinject: line 173: md5sum: command not found
cp: '/electra/usr/local/bin/bfinject4realz' and '/electra/usr/local/bin/bfinject4realz' are the same file
bfinject: line 184: tail: command not found
bfinject: line 184: cut: command not found
[+] Injecting into ''
[+] Getting Team ID from target application...
bfinject: line 199: tail: command not found
bfinject: line 199: cut: command not found
bfinject: line 199: cut: command not found
[+] WARNING: No Team ID found. Continuing regardless, but expect weird stuff to happen.
[+] Thinning dylib into non-fat arm64 image
[+] Signing injectable .dylib with Team ID  and platform entitlements...
jtool /electra/usr/local/bin/ signing error. barfing.

**Comment by JohnWong** [comment]
@kubacizek In Cydia.app, search and install `Core Utilities`. This solve the problem for me.

**Comment by kubacizek** [comment]
It worked! Thank you

**Comment by duanbibaojiaren** [comment]
@JohnWong   my iPhone  11.2.5 . In Cyia.app  search core  Utilities , Display sorry your device is not compatible with this package .  source   apt.cydiaba.cn.  What am I supposed to do?  tk
