### ISSUE TITLE
wget: command not found

### ISSUE THREAD

**Issue by snakeninny** [BishopFox/bfinject#4]
-bash-3.2# wget https://github.com/BishopFox/bfinject/raw/master/bfinject.tar
-bash: wget: command not found

**Comment by 0xhaggis** [comment]
Try running this before wget:

export PATH=$PATH:/jb/usr/bin:/jb/bin:/jb/sbin:/jb/usr/sbin:/jb/usr/local/bin:

**Comment by snakeninny** [comment]
Works! Thank you @0xhaggis
