### ISSUE TITLE
Script fails if the binary name contains a space

### ISSUE THREAD

**Issue by flockoffiles** [BishopFox/bfinject#7]
If the binary name contains a space, the script fails.

```
BINARY=`ps` -o pid,command $PID|tail -n1|sed 's/^\ *//g'|cut -f2 -d\ `
```

This cuts off the name after a space :-(

**Comment by flockoffiles** [comment]
Maybe, you could try this:
BINARY=`ps -o pid,command $PID|tail -n1|sed 's/^\ *//g'|cut -f2- -d\ `

Note the '-' after '-f2'

**Comment by 0xhaggis** [comment]
Good catch! Fixed in master.
