### ISSUE TITLE
Thread_create() returned 4, errno =2

### ISSUE THREAD

**Issue by Smethan** [BishopFox/bfinject#8]
Error is in the title. It happens no matter what app I try it on and I’ve tried restarting, rejailbreaking, all that jazz, none of its helped. The command I’m running is “bash bfinject -P Reddit.app -L test”. Any idea as to what’s up?

**Comment by 0xhaggis** [comment]
Please paste the output.

**Comment by Smethan** [comment]
Output of program: ] Attaching to PID 515[+] Electra detected.[+] Injecting into '/var/containers/Bundle/Application/582F507A-129F-4D2D-AA53-DE3B2104FEEE/Reddit.app/Reddit'[+] Getting Team ID from target application...[+] Thinning dylib into non-fat arm64 image[+] Signing injectable .dylib with Team ID 2TDUX39LX8 and platform entitlements...[bfinject] Getting tfp.[bfinject] Creating new remote thread[bfinject] Failed to create thread in remote process. Is it really an App Store app?[bfinject] thread_create() returned 4[bfinject] errno = 2 = No such file or directory[+] So long and thanks for all the fish.
Ps axwww output:   515   ??  Ss     0:07.95 /var/containers/Bundle/Application/582F507A-129F-4D2D-AA53-DE3B2104FEEE/Reddit.app/Reddit  626 s001  R+     0:00.00 grep Reddit
And I’m using Electra iOS 11.1.2

**Comment by Sacmunraga** [comment]
Yep, same error.

bash bfinject -P BbStudent.app -L decrypt
[+] Attaching to PID 1098
[+] Electra detected.
[+] Injecting into '/var/containers/Bundle/Application/CF5CEB1D-3323-4C19-BC90-5FB4F9402CA3/BbStudent.app/BbStudent'
[+] Getting Team ID from target application...
[+] Thinning dylib into non-fat arm64 image
[+] Signing injectable .dylib with Team ID YGV5TPV7E2 and platform entitlements...
[bfinject] Getting tfp.
[bfinject] Creating new remote thread
[bfinject] Failed to create thread in remote process. Is it really an App Store app?
[bfinject] thread_create() returned 4
[bfinject] errno = 2 = No such file or directory
[+] So long and thanks for all the fish.

**Comment by 0xhaggis** [comment]
Sorry, this is a jailbreak issue. I don't have any control over thread_create().

**Comment by Smethan** [comment]
Does that mean I would have to reinstall my jailbreak or wait for an update?

**Comment by Sacmunraga** [comment]
@0xhaggis It works. I disabled the "tweaks" option in Electra and Bingo! Thanks.

**Comment by MuchiMuchiPink** [comment]
this solves my problem as well. Thanks for finding this @Sacmunraga

**Comment by stek29** [comment]
did it solve problem for injecting into apple's apps? :P

**Comment by Sacmunraga** [comment]
@stek29, aren’t Apples apps decrypted to start out with?

**Comment by stek29** [comment]
@Sacmunraga I'm just trying to say that the only reason it didn't work is because of TF_PLATFORM flag being set on apps you were trying to inject into. You should contact jailbreakd to let it set your TF_PLATFORM too.
